spring:
#  liquibase:
#    change-log: classpath:db/changelog/changelog-master.xml
#    liquibase-schema: user
#    default-schema: user
  datasource:
    url: jdbc:postgresql://localhost:5432/User
    username: postgres
    password: Fateavernous123
    show-sql: true
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
  application:
    name: spring-boot-training

logging:
  level:
    com.example.springboottraining: INFO
    org.hibernate: INFO
    liquibase: INFO

server:
  error:
    include-message: always