spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/User
    username: postgres
    password: Fateavernous123
    show-sql: true
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: validate
  application:
    name: spring-boot-training
  flyway:
    default-schema: new_application
## select profile from default profile
  profiles:
    active: profile1

logging:
  level:
    com.example.springboottrainingv2: INFO
    org.hibernate: INFO

server:
  error:
    include-message: always